### ISSUE TITLE
Error fetching videos

### ISSUE THREAD

**Issue by mashkhurbek-mashrabov** [Oxke/ulauncher-ytwl#3]
I set up the extension following the docs. the API key is active. But I got an "Error fetching videos" error when I tried it.

![image](https://github.com/Oxke/ulauncher-ytwl/assets/72388700/0aa6cbbd-17b7-4dbe-b7a6-b12ecf2c4641)

**Comment by Oxke** [comment]
Do you get the same error by running `y l` on ulauncher?

**Comment by mashkhurbek-mashrabov** [comment]
> Do you get the same error by running `y l` on ulauncher?

I tried it and I got a "No new videos" message

**Comment by Oxke** [comment]
[You probably have to update Python](https://www.reddit.com/r/Python/comments/163ugsm/psa_as_of_python_311_datetimefromisoformat/)
(Now that I know this I will think about updating other things in the code to a more modern version of Python, since it turns out requires Python 3.11 anyways)

Otherwise, you can go modify the file `~./local/share/ulauncher/extensions/com.github.oxke.ulauncher-ytwl/main.py` and change lines 238, 473 and 671 by adding at the end `.replace("Z", "+00:00")`

**Comment by mashkhurbek-mashrabov** [comment]
it works
